config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  devise_for :saunners, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_scope :saunner do
    post 'saunners/guest_sign_in', to: 'public/saunners/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/saunners/my_page" => "saunners#show", as: "my_page"
    get "/saunners/edit" => "saunners#edit", as: "edit_saunners"
    patch "saunners" => "saunners#update"
    # いいね一覧
    get "/saunners/favorites" => "saunners#favorites", as: "favorites"
    # 退会確認画面
    get "/saunners/unsubscribe" => "saunners#unsubscribe", as: "unsubscribe"
    # 論理削除用のルーティング
    patch "/saunners/withdrawal" => "saunners#withdrawal", as: "withdrawal"

    resources :saunas do
      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
        get "search_tag" => "posts#search_tag"
      end
    end

    resources :chat_groups do
      get "join" => "chat_groups#join"
      delete "all_destroy" => 'chat_groups#all_destroy'
      resources :chats, only: [:create, :destroy]
    end

    resources :notifications, only: [:index]

    get "/search" => "searches#search", as: "search"

    resources :contacts, only: [:new, :create]

    resources :products, only: [:index, :show]
    resources :cart_products, expect: [:new, :show, :edit] do
      delete "/cart_products/destroy_all" => "cart_products#destroy_all", as: "destroy_all"
    end
    post "/orders/confirm" => "orders#confirm", as: "confirm"
    get "/orders/complete" => "orders#complete", as: "complete"
    resources :orders, expect: [:edit, :update, :destroy]
    resources :shipping_addresses, expect: [:new, :show]
  end

  namespace :admin do
    resources :saunners, expect: [:new, :create, :destroy]
    resources :saunas, expect: [:new, :create]
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show]
    resources :products
    resources :genres, expect: [:new, :show]
    resources :orders, only: [:show, :index, :update]
    resources :order_products, only: [:update]
    resources :chat_groups, only: [:show, :index] do
      delete "all_destroy" => 'admin/chat_groups#all_destroy'
    end
    root "homes#top"
  end

  get "/admin" => "admin/homes#top", as: "admin"
  get "/admin/search" => "admin/searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :saunner
  has_many :order_products, dependent: :destroy


  enum payment_method: {credit_card: 0, transfer: 1 }

  enum order_status: {
    waiting: 0,
    paid_up: 1,
    making: 2,
    preparing: 3,
    shipped: 4
  }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
    @subtotal = 0
  end

  def index
    @orders = Order.page(params[:page]).per(10).order(created_at: :desc)
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_products.update_all(production_status: 1)
      @order.order_products == "waiting"
    end
    flash[:notice] = "更新完了しました"
    redirect_to request.referer
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class='container px-5 px-sm-0'>
  <h2 class="mt-5">注文履歴一覧</h2>
  <table class="table table-hover mt-3">
    <thead>
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <% @orders.each do |order| %>
    <tbody>
      <tr onclick='window.location="<%= '/admin/orders/' + order.id.to_s %>"' role="link">
        <td><%= order.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= order.saunner.last_name + order.saunner.first_name %></td>
        <td><%= order.order_products.all.sum(:quantity) %></td>
        <td><%= order.order_status_i18n %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <div class="text-center pagination"><%= paginate @orders %></div>
</div>

app/views/admin/orders/show.html.erb
<div class='container px-5 px-sm-0'>
  <h2 class="mt-5">注文履歴詳細</h2>
  <table>
    <tr>
      <th>購入者</th>
      <td><%= @order.saunner.last_name + @order.saunner.first_name %></td>
    </tr>
    <tr>
      <th>注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td>
        〒<%= @order.postcode %><% @order.address %><br>
        <%= @order.name %>
      </td>
    </tr>
    <tr>
      <th>支払方法</th>
      <td><%= @order.payment_method_i18n %></td>
    </tr>
    <tr>
      <th>注文ステータス</th>
      <td>
        <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
          <%= f.select :order_status, Order.order_statuses_i18n.invert, {prompt: false} %>
          <%= f.submit "更新", class: "btn btn-sm btn-outline-success" %>
        <% end %>
      </td>
    </tr>
  </table>
  <div class="mt-3 row">
    <div class="col-8">
      <table class="table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_products.each do |order_product| %>
          <tr>
            <td><%= order_product.product.name %></td>
            <td><%= ((order_product.product.price * 1.1).floor).to_s(:delimited) %></td>
            <td><%= order_product.quantity %></td>
            <td><%= ((order_product.product.price * 1.1).floor * order_product.quantity).to_s(:delimited) %></td>
            <td>
              <%= form_with model: order_product, url: admin_order_product_path(order_product), method: :patch do |f| %>
                <%= f.select :production_status, OrderProduct.production_statuses_i18n.invert, {prompt: false} %>
                <%= f.submit "更新", class: "btn btn-sm btn-outline-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
    <div class="col-4">
      <table>
        <tr>
          <th>商品合計</th>
          <td>
            <% @order_products.each do |f| %>
              <% @subtotal += (f.product.price * 1.1).floor * f.quantity %>
            <% end %>
            ¥<%= @subtotal.to_s(:delimited) %>
          </td>
        </tr>
        <tr>
          <th>送料</th>
          <td>
            <%= (@order.shipping_fee).to_s(:delimited) %>
          </td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= (@order.total_price).to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>
</div>