config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  devise_for :saunners, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_scope :saunner do
    post 'saunners/guest_sign_in', to: 'public/saunners/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/saunners/my_page" => "saunners#show", as: "my_page"
    get "/saunners/edit" => "saunners#edit", as: "edit_saunners"
    patch "saunners" => "saunners#update"
    # いいね一覧
    get "/saunners/favorites" => "saunners#favorites", as: "favorites"
    # 退会確認画面
    get "/saunners/unsubscribe" => "saunners#unsubscribe", as: "unsubscribe"
    # 論理削除用のルーティング
    patch "/saunners/withdrawal" => "saunners#withdrawal", as: "withdrawal"

    resources :saunas do
      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
        get "search_tag" => "posts#search_tag"
      end
    end

    resources :chat_groups do
      get "join" => "chat_groups#join"
      delete "all_destroy" => 'chat_groups#all_destroy'
      resources :chats, only: [:create, :destroy]
    end

    resources :notifications, only: [:index]

    get "/search" => "searches#search", as: "search"

    resources :contacts, only: [:new, :create]

    resources :products, only: [:index, :show]
    resources :cart_products, expect: [:new, :show, :edit] do
      delete "/cart_products/destroy_all" => "cart_products#destroy_all", as: "destroy_all"
    end
    post "/orders/confirm" => "orders#confirm", as: "confirm"
    get "/orders/complete" => "orders#complete", as: "complete"
    resources :orders, expect: [:edit, :update, :destroy]
    resources :shipping_addresses, expect: [:new, :show]
  end

  namespace :admin do
    resources :saunners, expect: [:new, :create, :destroy]
    resources :saunas, expect: [:new, :create]
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show]
    resources :products
    resources :genres, expect: [:new, :show]
    resources :orders, only: [:show, :index, :update]
    resources :order_products, only: [:update]
    resources :chat_groups, only: [:show, :index] do
      delete "all_destroy" => 'admin/chat_groups#all_destroy'
    end
    root "homes#top"
  end

  get "/admin" => "admin/homes#top", as: "admin"
  get "/admin/search" => "admin/searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page]).per(10)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルを登録しました"
      redirect_to admin_genres_path
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update
      flash[:notice] = "ジャンルを更新しました"
      redirect_to admin_genres_path
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    if @genre.destroy
      redirect_to admin_genres_path
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_edit_form.html.erb
<%= form_with model: genre, url: {controller: 'admin/genres', action: 'update'} do |f| %>
<div class="form-inline pt-5">
  <div class="pl-5">ジャンル</div>
  <%= f.text_field :name, class: "ml-5", placeholder: "ジャンル名" %>
  <%= f.submit "登録" , class: "btn btn-sm btn-outline-success col-md-offset-6 ml-5" %>
</div>
<% end %>

app/views/admin/genres/_form.html.erb
<%= form_with model: genre, url: {controller: 'admin/genres', action: 'create'} do |f| %>
<div class="form-inline pt-5">
  <div class="pl-5">ジャンル</div>
  <%= f.text_field :name, class: "ml-5", placeholder: "ジャンル名" %>
  <%= f.submit "登録" , class: "btn btn-sm btn-outline-success col-md-offset-6 ml-5" %>
</div>
<% end %>

app/views/admin/genres/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>ジャンル</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% genres.each do |genre| %>
    <tr>
      <td></td>
      <td><%= genre.name %></td>
      <td><%= link_to "編集", edit_admin_genre_path(genre.id), class: "btn btn-sm btn-outline-success" %></td>
      <td><%= link_to '削除', admin_genre_path(genre.id), method: :delete, data: { confirm: '本当に削除しますか？' } , class: "btn btn-sm btn-outline-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination"><%= paginate genres %></div>

app/views/admin/genres/edit.html.erb
<div class="container px-5 px-sm-0" style="margin-bottom: 630px;">
  <h2>ジャンル編集</h2>
  <%= render "edit_form", genre: @genre %>
</div>

app/views/admin/genres/index.html.erb
<div class="container px-5 px-sm-0 admin_genres">
  <h2>ジャンル一覧・追加</h2>
  <%= render "form", genre: @genre %>
  <div class="mt-5">
    <%= render "index", genres: @genres %>
  </div>
</div>