config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  devise_for :saunners, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_scope :saunner do
    post 'saunners/guest_sign_in', to: 'public/saunners/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/saunners/my_page" => "saunners#show", as: "my_page"
    get "/saunners/edit" => "saunners#edit", as: "edit_saunners"
    patch "saunners" => "saunners#update"
    # いいね一覧
    get "/saunners/favorites" => "saunners#favorites", as: "favorites"
    # 退会確認画面
    get "/saunners/unsubscribe" => "saunners#unsubscribe", as: "unsubscribe"
    # 論理削除用のルーティング
    patch "/saunners/withdrawal" => "saunners#withdrawal", as: "withdrawal"

    resources :saunas do
      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
        get "search_tag" => "posts#search_tag"
      end
    end

    resources :chat_groups do
      get "join" => "chat_groups#join"
      delete "all_destroy" => 'chat_groups#all_destroy'
      resources :chats, only: [:create, :destroy]
    end

    resources :notifications, only: [:index]

    get "/search" => "searches#search", as: "search"

    resources :contacts, only: [:new, :create]

    resources :products, only: [:index, :show]
    resources :cart_products, expect: [:new, :show, :edit] do
      delete "/cart_products/destroy_all" => "cart_products#destroy_all", as: "destroy_all"
    end
    post "/orders/confirm" => "orders#confirm", as: "confirm"
    get "/orders/complete" => "orders#complete", as: "complete"
    resources :orders, expect: [:edit, :update, :destroy]
    resources :shipping_addresses, expect: [:new, :show]
  end

  namespace :admin do
    resources :saunners, expect: [:new, :create, :destroy]
    resources :saunas, expect: [:new, :create]
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show]
    resources :products
    resources :genres, expect: [:new, :show]
    resources :orders, only: [:show, :index, :update]
    resources :order_products, only: [:update]
    resources :chat_groups, only: [:show, :index] do
      delete "all_destroy" => 'admin/chat_groups#all_destroy'
    end
    root "homes#top"
  end

  get "/admin" => "admin/homes#top", as: "admin"
  get "/admin/search" => "admin/searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    # ステータス有効のみ表示/新規投稿順3つのみ表示
    @new_posts = Post.limit(3).order(created_at: :desc)
    @new_saunas = Sauna.where(is_active: false).limit(3).order(created_at: :desc)
    @new_contacts = Contact.limit(3).order(created_at: :desc)
    @saunners = Saunner.all
    @saunas = Sauna.all
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/_contact.html.erb
<div class="container-fluid pt-5 pl-3">
  <div class="row">
    <% new_contacts.each do |contact| %>
    <%= link_to admin_contact_path(contact.id) do %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= contact.title %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= contact.name %></h6>
        <p class="card-text"><%= contact.content %></p>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/admin/homes/_post.html.erb
<div class="container-fluid pt-5 pl-3">
  <div class="row">
    <% new_posts.each do |post| %>
    <%= link_to admin_post_path(post.id) do %>
    <div class="col mb-3">
      <div class="card" style="width: 18rem;">
        <%= image_tag post.get_sauna_image, size: "286x180" %>
        <div class="card-body">
          <table>
            <thead>
              <tr>
                <td style="font-size: small;">
                <%= post.saunner.nickname %>さん
                </td>
              </tr>
              <tr>
                <th>
                 <a style="color: blue; clamp(1px, 18px, 18px);"><%= post.sauna.name %></a><br>
                 <a style="color: gray; font-size: small;">[<%= post.sauna.prefecture %>]</a>
                </th>
              </tr>
            </thead>
            <tbody style="font-size: small;">
              <tr>
                <td>サウナ室温度：<%= post.sauna_temperature %>℃</td>
                <td class="pl-3">水風呂温度：<%= post.mizu_temperature %>℃</td>
              </tr>
              <tr>
                <td>サウナ時間：<%= post.sauna_minutes %>分</td>
                <td class="pl-3">水風呂時間：<%= post.mizu_minutes %>分</td>
              </tr>
              <tr>
                <td>ととのい時間：<%= post.totonoi_minutes %>分</td>
                <td class="pl-3">セット数：<%= post.sauna_times %>回</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
  </div>
</div>

app/views/admin/homes/_sauna.html.erb
<div class="container-fluid pt-5 pl-3">
  <div class="row">
    <% new_saunas.each do |sauna| %>
    <%= link_to admin_sauna_path(sauna.id) do %>
    <div class="col mb-3">
      <div class="card" style="width: 18rem;">
        <%= image_tag sauna.get_store_image, width: '100%', height: '50%' %>
        <div class="card-body">
          <h5 class="card-title"><%= sauna.name %><br><small class="text-muted"><%= sauna.prefecture %></small></h5>
          <p class="card-text">サウナ室温度：<%= sauna.sauna_temperature %>℃</p>
          <p class="card-text">水風呂温度：<%= sauna.mizu_temperature %>℃</p>
          <p class="card-text">ととのいスポット：<%= sauna.break_space %></p>
          <p class="card-text top-sauna">料金：<%= sauna.fee %></p>
          <p class="card-text top-sauna">定休日：<%= sauna.holiday %></p>
          <strong style="color: red;">ステータス：
            <% if sauna.is_active %>
            <span>公開中</span>
　　        <% else %>
            <span>公開停止中</span>
　　        <% end %>
　　      </strong>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="container">
    <h5 class="pt-5"><新規サ活投稿></h5>
    <%= render 'post', new_posts: @new_posts, saunas: @saunas, saunners: @saunners %>
  </div>
  <div class="container">
    <h5 class="pt-5"><新規施設情報></h5>
    <%= render 'sauna', new_saunas: @new_saunas %>
  </div>
  <div class="container">
    <h5 class="pt-5"><お問合せ情報></h5>
    <%= render 'contact', new_contacts: @new_contacts %>
  </div>
</div>