config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  devise_for :saunners, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_scope :saunner do
    post 'saunners/guest_sign_in', to: 'public/saunners/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/saunners/my_page" => "saunners#show", as: "my_page"
    get "/saunners/edit" => "saunners#edit", as: "edit_saunners"
    patch "saunners" => "saunners#update"
    # いいね一覧
    get "/saunners/favorites" => "saunners#favorites", as: "favorites"
    # 退会確認画面
    get "/saunners/unsubscribe" => "saunners#unsubscribe", as: "unsubscribe"
    # 論理削除用のルーティング
    patch "/saunners/withdrawal" => "saunners#withdrawal", as: "withdrawal"

    resources :saunas do
      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
        get "search_tag" => "posts#search_tag"
      end
    end

    resources :chat_groups do
      get "join" => "chat_groups#join"
      delete "all_destroy" => 'chat_groups#all_destroy'
      resources :chats, only: [:create, :destroy]
    end

    resources :notifications, only: [:index]

    get "/search" => "searches#search", as: "search"

    resources :contacts, only: [:new, :create]

    resources :products, only: [:index, :show]
    resources :cart_products, expect: [:new, :show, :edit] do
      delete "/cart_products/destroy_all" => "cart_products#destroy_all", as: "destroy_all"
    end
    post "/orders/confirm" => "orders#confirm", as: "confirm"
    get "/orders/complete" => "orders#complete", as: "complete"
    resources :orders, expect: [:edit, :update, :destroy]
    resources :shipping_addresses, expect: [:new, :show]
  end

  namespace :admin do
    resources :saunners, expect: [:new, :create, :destroy]
    resources :saunas, expect: [:new, :create]
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show]
    resources :products
    resources :genres, expect: [:new, :show]
    resources :orders, only: [:show, :index, :update]
    resources :order_products, only: [:update]
    resources :chat_groups, only: [:show, :index] do
      delete "all_destroy" => 'admin/chat_groups#all_destroy'
    end
    root "homes#top"
  end

  get "/admin" => "admin/homes#top", as: "admin"
  get "/admin/search" => "admin/searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :genre
  has_many :cart_products, dependent: :destroy
  has_many :order_products, dependent: :destroy

  has_one_attached :product_image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :product_image, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.page(params[:page]).per(10)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to admin_products_path
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "商品を登録しました"
      redirect_to admin_products_path
    else
      flash[:notice] = "登録に失敗しました"
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "商品を更新しました"
      redirect_to admin_products_path
    else
      flash[:notice] = "更新に失敗しました"
      render 'edit'
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :introduction, :genre_id, :product_image, :price, :is_active)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_edit_form.html.erb
<%= form_with model: product, url: {controller: 'admin/products', action: 'update'} do |f| %>
<div class="pt-5">
  <div class="form-group row">
    <%= f.label :product_image, "商品画像", class: "col-md-2" %>
    <%= f.file_field :product_image, class: "col-md-4", accept: 'image/*' %>
  </div>
  <div class="form-group row">
    <%= f.label :name, "商品名", class: "col-md-2" %>
    <%= f.text_field :name, class: "col-md-4" %>
  </div>
  <div class="form-group row">
    <%= f.label :introduction, "商品説明", class: "col-md-2" %>
    <%= f.text_area :introduction, class: "col-md-4", size: "100x10", placeholder: "ここに説明文を記述します" %>
  </div>
  <div class="form-group row">
    <%= f.label :name, "ジャンル", class: "col-md-2" %>
    <%= f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] }, { include_blank: '選択してください'} %>
  </div>
  <div class="form-group row">
    <%= f.label :price, "税抜価格", class: "col-md-2" %>
    <%= f.text_field :price, class: "col-md-2", placeholder: "1,000" %>円
  </div>
  <div class="form-group row">
    <%= f.label :is_active, "販売ステータス", class: "col-md-2" %>
    <%= f.radio_button :is_active, :true %>
    <%= f.label :is_active, "販売中", {value: true, style: "display: inline-block;"} %>
    <%= f.radio_button :is_active, :false %>
    <%= f.label :is_active, "販売停止中", {value: false, style: "display: inline-block;"} %>
  </div>
  <div class="pl-5 pt-3">
    <%= f.submit "登録" , class: "btn btn-sm btn-outline-success col-md-offset-6 ml-5" %>
  </div>
</div>
<% end %>

app/views/admin/products/_form.html.erb
<%= form_with model: product, url: {controller: 'admin/products', action: 'create'} do |f| %>
<div class="pt-5">
  <div class="form-group row">
    <%= f.label :product_image, "商品画像", class: "col-md-2" %>
    <%= f.file_field :product_image, class: "col-md-4", accept: 'image/*' %>
  </div>
  <div class="form-group row">
    <%= f.label :name, "商品名", class: "col-md-2" %>
    <%= f.text_field :name, class: "col-md-4" %>
  </div>
  <div class="form-group row">
    <%= f.label :introduction, "商品説明", class: "col-md-2" %>
    <%= f.text_area :introduction, class: "col-md-4", size: "100x10", placeholder: "ここに説明文を記述します" %>
  </div>
  <div class="form-group row">
    <%= f.label :name, "ジャンル", class: "col-md-2" %>
    <%= f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] }, { include_blank: '選択してください'} %>
  </div>
  <div class="form-group row">
    <%= f.label :price, "税抜価格", class: "col-md-2" %>
    <%= f.text_field :price, class: "col-md-2", placeholder: "1,000" %>円
  </div>
  <div class="form-group row">
    <%= f.label :is_active, "販売ステータス", class: "col-md-2" %>
    <%= f.radio_button :is_active, :true %>
    <%= f.label :is_active, "販売中", {value: true, style: "display: inline-block;"} %>
    <%= f.radio_button :is_active, :false %>
    <%= f.label :is_active, "販売停止中", {value: false, style: "display: inline-block;"} %>
  </div>
  <div class="pl-5 pt-3">
    <%= f.submit "登録" , class: "btn btn-sm btn-outline-success col-md-offset-6 ml-5" %>
  </div>
</div>
<% end %>

app/views/admin/products/_index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% products.each do |product| %>
    <tr onclick='window.location="<%= '/admin/products/' + product.id.to_s %>"' role="link" >
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td>¥<%= product.price.to_s(:delimited) %></td>
      <td><%= product.genre.name %></td>
      <td>
        <% if product.is_active %>
          <span>販売中</span>
        <% else %>
          <span>販売停止中</span>
        <% end %>
      </td>
      <td><%= link_to "編集", edit_admin_product_path(product.id), class: "btn btn-sm btn-outline-success" %></td>
      <td><%= link_to '削除', admin_product_path(product.id), method: :delete, data: { confirm: '本当に削除しますか？' } , class: "btn btn-sm btn-outline-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination"><%= paginate products %></div>

app/views/admin/products/_show.html.erb
<table class="table">
  <tbody>
    <tr>
      <th style="width: 150px;">商品名</th>
      <td><%= product.name %></td>
    </tr>
    <tr>
      <th>商品説明</th>
      <td><%= product.introduction %></td>
    </tr>
    <tr>
      <th>ジャンル</th>
      <td><%= product.genre.name %></td>
    </tr>
    <tr>
      <th>
        <p>税込価格</p>
        <p>(税抜価格)</p>
      </th>
      <td>
        <p>¥<%= ((product.price * 1.1).floor).to_s(:delimited) %></p>
        <p>(¥<%= (product.price).to_s(:delimited) %>)</p>
      </td>
    </tr>
  </tbody>
</table>

app/views/admin/products/edit.html.erb
<div class="container px-5 px-sm-0 new_admin_product">
  <h2>商品編集</h2>
  <div class="mt-5">
    <%= render "edit_form", product: @product %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container px-5 px-sm-0 admin_products">
  <h2>商品一覧</h2>
  <div class="mt-5">
    <div><%= link_to '+', new_admin_product_path, class: 'btn btn-outline-dark' %></div>
    <%= render "index", products: @products %>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container px-5 px-sm-0 new_admin_product">
  <h2>商品新規登録</h2>
  <%= render "/layouts/errors", obj: @product %>
  <div class="mt-5">
    <%= render "form", product: @product %>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container px-5 px-sm-0 admin_product">
  <h2>商品詳細</h2>
  <div class="row mt-5">
    <div class="col">
      <%= image_tag @product.product_image, class: "product_show_image" %>
      <table>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @product.is_active %>
              <span>販売中</span>
            <% else %>
              <span>販売停止中</span>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    <div class="col">
      <%= render "show", product: @product %>
      <%= link_to "編集", edit_admin_product_path(@product.id), class: "btn btn-sm btn-outline-success" %>
    </div>
  </div>
  <p><%= link_to "≤商品一覧", admin_products_path %></p>
</div>